apiVersion: apps/v1
kind: Deployment
metadata:
  name: discoveryserver-deployment
spec:
  selector:
    matchLabels:
      app: discoveryserver
  replicas: 1
  template:
    metadata:
      labels:
        app: discoveryserver
    spec:
      containers:
        - name: discoveryserver
          image: emreoytun/discoveryserver:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8888  # Updated to match the application's port
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: discoveryserver-ssvc
spec:
  selector:
    app: discoveryserver
  ports:
    - protocol: "TCP"
      port: 80             # Port exposed by the service
      targetPort: 8888     # Port on which the application is listening
  type: LoadBalancer
